const actionTypes = {
  REQUESTEDROUTE: 'REQUESTEDROUTE',
  CHANGEACTIVEROUTE: 'CHANGEACTIVEROUTE',
  LASTPATH: 'LASTPATH',
  USER: 'USER',
  PROFILE: 'PROFILE',
  PROPERTY: 'PROPERTY',
  SEARCHPROPERTY: 'SEARCHPROPERTY',
  SEARCHOPTIONS: 'SEARCHOPTIONS',
  SEARCHCOUNT: 'SEARCHCOUNT',
  BUYER_CHATROOMS: 'BUYER_CHATROOMS',
  SELLER_CHATROOMS: 'SELLER_CHATROOMS',
  CHATROOM_DATA: 'CHATROOM_DATA',
  COMMENTS: 'COMMENTS',
  ADD_FAVOURITE: 'ADD_FAVOURITE',
  REMOVE_FAVOURITE: 'REMOVE_FAVOURITE',
  USER_VERIFIED: "USER_VERIFIED"
};

export default actionTypes;
